apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: ClusterIP # or NodePort
  selector:
    app: rabbitmq
  ports:
    - name: http
      protocol: TCP
      port: 15672
      targetPort: 15672
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672

# To delete resources created with these files:
# kubectl delete -f ./

# To apply / create resources with these files:
# kubectl apply -f ./

# To scale down pods
# kubectl scale deployment --replicas=[int] [deployment](ex. gateway)
